### ISSUE TITLE
Resolve the deprecated functions qemu compilation error

### ISSUE THREAD

**Issue by niravnery** [davidsaOpenu/simulator#14]
With gcc version: "gcc version 4.4.7 (Ubuntu/Linaro 4.4.7-1ubuntu2)" we get the following error when trying to compile QEMU:

cc1: warnings being treated as errors
ui/vnc-tls.c: In function ‘vnc_tls_client_setup’:
ui/vnc-tls.c:313: error: ‘gnutls_kx_set_priority’ is deprecated (declared at /usr/include/gnutls/compat.h:342)
ui/vnc-tls.c:320: error: ‘gnutls_certificate_type_set_priority’ is deprecated (declared at /usr/include/gnutls/compat.h:347)
ui/vnc-tls.c:327: error: ‘gnutls_protocol_set_priority’ is deprecated (declared at /usr/include/gnutls/compat.h:344)
make: **\* [ui/vnc-tls.o] Error 1

Adding the no-deprecated-declarations flag to QEMU/Makefile resolves it but we should probably handle this differently.
QEMU_CFLAGS += -g -Wno-deprecated-declarations

**Comment by davidsaOpenu** [comment]
opened a ticket to upgrade the version of the qemu
