### ISSUE TITLE
tht submodule missing on clone.

### ISSUE THREAD

**Issue by someuser77** [davidsaOpenu/simulator#23]
Hello,
I've cloned your repo using git clone and the osc-osd makefile is failing because the tgt submodule is missing.
"git submodule init" and "git submodule update" failed with the error:
"No submodule mapping found in .gitmodules for path 'eVSSIM/osc-osd/tgt'"
I'm missing the correct steps to clone the tgt submodule.
What are the correct steps to clone the submodule?
What is the correct git repo url to use?
If i've missed a document describing it then at least this issue will server those searching for it.

**Comment by davidsaOpenu** [comment]
hello, sorry we are not using issue tracker. Just decided to close all issues and saw your question. 
try 

> cd eVSSIM/osc-osd 
> and then run 
> make target

Please contact me davidsa@openu.ac.il if you want to contribute to the project and I will supply to you the necessary guidance.
